name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'codewars/riscv' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install QEMU static binaries
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:7.1.0-2 --reset -p yes
          ls /proc/sys/fs/binfmt_misc/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          # Make the image available in next step
          load: true
          platforms: linux/riscv64
          tags: ghcr.io/codewars/riscv:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run multiply example
        run: bin/run multiply

      - name: Run multiply-failing example
        run: bin/run multiply-failing || true

      - name: Run syntax-error example
        run: bin/run syntax-error || true

      - name: Run invalid-regname example
        run: bin/run invalid-regname || true
