# Build and push a Docker image to GitHub Container Registry when
# a new tag is pushed.
name: Push Image

on:
  push:
    tags:
      - "*"

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'codewars/riscv' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Install qemu-user-static
        run: |
          cd /tmp
          wget -q -O qemu-user-static.deb http://ftp.us.debian.org/debian/pool/main/q/qemu/qemu-user-static_7.1+dfsg-2+b1_amd64.deb
          sudo apt install ./qemu-user-static.deb
          rm ./qemu-user-static.deb
          qemu-riscv64-static --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: codewars
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/riscv64
          tags: |
            ghcr.io/codewars/riscv:latest
            ghcr.io/codewars/riscv:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
